using InventoryManagementSystem.EntityFrameworkCore;
using Xunit;

namespace InventoryManagementSystem.EntityFrameworkCore;

public class InventoryManagementSystemEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<InventoryManagementSystemEntityFrameworkCoreFixture>
{

}
