using Volo.Abp;

namespace InventoryManagementSystem.EntityFrameworkCore;

public abstract class InventoryManagementSystemEntityFrameworkCoreTestBase : InventoryManagementSystemTestBase<InventoryManagementSystemEntityFrameworkCoreTestModule>
{

}
