using Xunit;

namespace InventoryManagementSystem.EntityFrameworkCore;

[CollectionDefinition(InventoryManagementSystemTestConsts.CollectionDefinitionName)]
public class InventoryManagementSystemEntityFrameworkCoreCollection : ICollectionFixture<InventoryManagementSystemEntityFrameworkCoreFixture>
{

}
