using InventoryManagementSystem.EntityFrameworkCore;

namespace InventoryManagementSystem;

public class InventoryManagementSystemWebCollection : InventoryManagementSystemEntityFrameworkCoreCollectionFixtureBase
{

}
